apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  annotations:
    build.appstudio.openshift.io/repo: https://github.com/jcapiitao/fedora-coreos-config?rev={{revision}}
    build.appstudio.redhat.com/commit_sha: '{{revision}}'
    build.appstudio.redhat.com/target_branch: '{{target_branch}}'
    pipelinesascode.tekton.dev/cancel-in-progress: "false"
    pipelinesascode.tekton.dev/max-keep-runs: "3"
    pipelinesascode.tekton.dev/on-cel-expression: event == "push" && target_branch
      == "testing-devel"
  creationTimestamp: null
  labels:
    appstudio.openshift.io/application: fcos-pipeline-jcapitao
    appstudio.openshift.io/component: fcos-pipeline-rawhide-jcapitao
    pipelines.appstudio.openshift.io/type: build
  name: fcos-pipeline-rawhide-jcapitao-on-push
  namespace: coreos-tenant
spec:
  params:
  - name: git-url
    value: '{{source_url}}'
  - name: revision
    value: '{{revision}}'
  - name: output-image
    value: quay.io/konflux-fedora/coreos-tenant/fcos-pipeline-rawhide-jcapitao:{{revision}}
  - name: dockerfile
    value: Dockerfile
  - name: path-context
    value: .
  pipelineRef:
    name: build-pipeline
  taskRunTemplate: {}
  workspaces:
  - name: git-auth
    secret:
      secretName: '{{ git_auth_secret }}'
status: {}
